### ISSUE TITLE
VerifySignature non effettua la verifica corretta.

### ISSUE THREAD

**Issue by claudiopizzillo** [danielegiallonardo/spid-aspnetcore#1]
VerifySignature non effettua la verifica in maniera corretta: 

1) devono essere firmate sia la response che l'assertion;
2) la firma della response deve essere verificata col certificato esposto nel metadata dell'IdP.

Un esempio di verifica corretta che supera i test dello spid-saml-check:
`

                try
                {
                    XmlDocument metadata = new XmlDocument
                    {
                        PreserveWhitespace = true
                    };
                    metadata.Load(METADATAURL);
                    XmlNodeList MetadataNodeList = metadata.SelectNodes("//*[local-name()='Signature']");
                    SignedXml signedMetadataXml = new SignedXml(metadata);
                    signedMetadataXml.LoadXml((XmlElement)MetadataNodeList[0]);
                    var x509dataMetadata = signedMetadataXml.Signature.KeyInfo.OfType<KeyInfoX509Data>().First();
                    var publicMetadataCert = x509dataMetadata.Certificates[0] as X509Certificate2;

                    SignedXml signedXml = new SignedXml(signedDocument);
                    XmlNodeList nodeList = (signedDocument.GetElementsByTagName("ds:Signature")?.Count > 1) ?
                                                   signedDocument.GetElementsByTagName("ds:Signature") :
                                                   (signedDocument.GetElementsByTagName("ns2:Signature")?.Count > 1) ?
                                                   signedDocument.GetElementsByTagName("ns2:Signature") :
                                                   signedDocument.GetElementsByTagName("Signature");

                    signedXml.LoadXml((XmlElement)nodeList[0]);
                    return signedXml.CheckSignature(publicMetadataCert, true);
                }
                catch (Exception ex)
                {
                    return false;
                }
`

**Comment by danielegiallonardo** [comment]
Fix aggiunto e verificato con spid-saml-check
